from django.urls import path
from fasto import fasto_views
app_name='fasto'
urlpatterns = [
    path('',fasto_views.index,name="index"),
    path('index/',fasto_views.index,name="index"),
    path('index-2/',fasto_views.index_2,name="index-2"),
    path('projects',fasto_views.projects,name="projects"),
    path('contacts',fasto_views.contacts,name="contacts"),
    path('kanban',fasto_views.kanban,name="kanban"),
    path('calendar',fasto_views.calendar,name="calendar"),
    path('messages',fasto_views.messages,name="messages"),

    path('app-profile/',fasto_views.app_profile,name="app-profile"),
    path('post-details/',fasto_views.post_details,name="post-details"),
    path('email-compose/',fasto_views.email_compose,name="email-compose"),
    path('email-inbox/',fasto_views.email_inbox,name="email-inbox"),
    path('email-read/',fasto_views.email_read,name="email-read"),
    path('app-calender/',fasto_views.app_calender,name="app-calender"),
    path('ecom-product-grid/',fasto_views.ecom_product_grid,name="ecom-product-grid"),
    path('ecom-product-list/',fasto_views.ecom_product_list,name="ecom-product-list"),
    path('ecom-product-detail/',fasto_views.ecom_product_detail,name="ecom-product-detail"),
    path('ecom-product-order/',fasto_views.ecom_product_order,name="ecom-product-order"),
    path('ecom-checkout/',fasto_views.ecom_checkout,name="ecom-checkout"),
    path('ecom-invoice/',fasto_views.ecom_invoice,name="ecom-invoice"),
    path('ecom-customers/',fasto_views.ecom_customers,name="ecom-customers"),
    path('chart-flot/',fasto_views.chart_flot,name="chart-flot"),
    path('chart-morris/',fasto_views.chart_morris,name="chart-morris"),
    path('chart-chartjs/',fasto_views.chart_chartjs,name="chart-chartjs"),
    path('chart-chartist/',fasto_views.chart_chartist,name="chart-chartist"),
    path('chart-sparkline/',fasto_views.chart_sparkline,name="chart-sparkline"),
    path('chart-peity/',fasto_views.chart_peity,name="chart-peity"),

    path('ui-accordion/',fasto_views.ui_accordion,name="ui-accordion"),
    path('ui-alert/',fasto_views.ui_alert,name="ui-alert"),
    path('ui-badge/',fasto_views.ui_badge,name="ui-badge"),
    path('ui-button/',fasto_views.ui_button,name="ui-button"),
    path('ui-modal/',fasto_views.ui_modal,name="ui-modal"),
    path('ui-button-group/',fasto_views.ui_button_group,name="ui-button-group"),
    path('ui-list-group/',fasto_views.ui_list_group,name="ui-list-group"),
    path('ui-media-object/',fasto_views.ui_media_object,name="ui-media-object"),
    path('ui-card/',fasto_views.ui_card,name="ui-card"),
    path('ui-carousel/',fasto_views.ui_carousel,name="ui-carousel"),
    path('ui-dropdown/',fasto_views.ui_dropdown,name="ui-dropdown"),
    path('ui-popover/',fasto_views.ui_popover,name="ui-popover"),
    path('ui-progressbar/',fasto_views.ui_progressbar,name="ui-progressbar"),
    path('ui-tab/',fasto_views.ui_tab,name="ui-tab"),
    path('ui-typography/',fasto_views.ui_typography,name="ui-typography"),
    path('ui-pagination/',fasto_views.ui_pagination,name="ui-pagination"),
    path('ui-grid/',fasto_views.ui_grid,name="ui-grid"),
    

    path('uc-select2/',fasto_views.uc_select2,name="uc-select2"),
    path('uc-nestable/',fasto_views.uc_nestable,name="uc-nestable"),
    path('uc-noui-slider/',fasto_views.uc_noui_slider,name="uc-noui-slider"),
    path('uc-sweetalert/',fasto_views.uc_sweetalert,name="uc-sweetalert"),
    path('uc-toastr/',fasto_views.uc_toastr,name="uc-toastr"),
    path('map-jqvmap/',fasto_views.map_jqvmap,name="map-jqvmap"),
    path('uc-lightgallery/',fasto_views.uc_lightgallery,name="uc-lightgallery"),
    path('uc-lightgallery/',fasto_views.uc_lightgallery,name="uc-lightgallery"),
    path('widget-basic/',fasto_views.widget_basic,name="widget-basic"),

    path('form-element/',fasto_views.form_element,name="form-element"),
    path('form-wizard/',fasto_views.form_wizard,name="form-wizard"),
    path('form-editor/',fasto_views.form_editor,name="form-editor"),
    path('form-pickers/',fasto_views.form_pickers,name="form-pickers"),
    path('form-validation/',fasto_views.form_validation,name="form-validation"),

    path('table-bootstrap-basic/',fasto_views.table_bootstrap_basic,name="table-bootstrap-basic"),
    path('table-datatable-basic/',fasto_views.table_datatable_basic,name="table-datatable-basic"),


    path('page-login/',fasto_views.page_login,name="page-login"),
    path('page-register/',fasto_views.page_register,name="page-register"),
    path('page-forgot-password/',fasto_views.page_forgot_password,name="page-forgot-password"),
    path('page-lock-screen/',fasto_views.page_lock_screen,name="page-lock-screen"),
    path('page-empty/',fasto_views.page_empty,name="page-empty"),
    path('page-error-400/',fasto_views.page_error_400,name="page-error-400"),
    path('page-error-403/',fasto_views.page_error_403,name="page-error-403"),
    path('page-error-404/',fasto_views.page_error_404,name="page-error-404"),
    path('page-error-500/',fasto_views.page_error_500,name="page-error-500"),
    path('page-error-503/',fasto_views.page_error_503,name="page-error-503"),
]